---
title: "git_00"
author: "Tyler Frasier"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse
’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   





<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both.   
And be one traveler, long I stood.   
And looked down one as far as I could.   
To where it bent in the undergrowth;    

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining with all his might:    
He did his very best to make.   
      The billows smooth and bright —    
And this was odd, because it was.   
      The middle of the night.    

The moon was shining sulkily,    
      Because she thought the sun.   
Had got no business to be there.   
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Mean, median, and mode, they form a trio,     
Describing data's center, in a way so clear, though.    
Standard deviation, it measures the spread,    
Uncertainty's realm, where predictions are bred.    

In regression's embrace, we seek to explain,    
The relationships hidden in the data's domain.    
Hypotheses tested, conclusions are drawn,    
In the realm of statistics, knowledge is dawned.    
